package:
  name: "conga"
  version: "1.0.0"

source:
  path: .

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python =3.9
    - pyteomics
    - pandas
    - numpy
    - scipy
    - tqdm
    - matplotlib

about:
  home: https://github.com/freejstone/CONGA
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Combined Open and Narrow searches via Group Analysis"

extra:
  recipe-maintainers:
    - freejstone