name: Create Release
run-name: ${{ github.actor }} is creating a github release

on:
  push:
    branches:
      - develop-package
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # steps for building assets
      - run: echo "REPLACE ME!" > "dist/*tar.gz"

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "dist/*tar.gz"
