name: test-with-data
run-name: ${{ github.actor }} is testing commands with sample data
on: 
  push:
    branches: [ develop-package ]
jobs:
  check-code-finishes:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
      - run: python3 -m pip install --upgrade pip pandas
      - run: python3 -m pip install --upgrade pip pyteomics
      - run: python3 -m pip install --upgrade pip numpy
      - run: python3 -m pip install --upgrade pip scipy
      - run: python3 -m pip install --upgrade pip matplotlib
      - run: python3 -m pip install --upgrade pip tqdm
      - run: python3 -m pip install --upgrade pip pytest
      - run: python3 ./src/CONGA.py --overwrite T --return_mass_mod_hist T --n_processes 3 --return_extra_mods T --seed 1 ./data/tide/narrow_example1.tide-search.txt ./data/tide/open_example1.tide-search.txt
      - run: python3 ./src/CONGA.py --overwrite T --dcy_prefix DECOY --score e-value --seed 1 ./data/comet/narrow_example1.comet.txt ./data/comet/open_example1.comet.txt
      - run: python3 ./src/CONGA.py --overwrite T --score hyperscore --seed 1 ./data/MS/narrow.tsv ./data/MS/open.tsv ./data/MS/tide-index.peptides.txt
      - run: cd src; python3 -m pytest ../tests/